version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    depends_on:
      - database
    networks:
      - librarynetwork

  database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - librarynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_DATABASE=library
      - MYSQL_USER=app
      - MYSQL_PASSWORD=testpassword
    volumes:
      - db_data:/var/lib/servermysql

volumes:
  db_data:

networks:
  librarynetwork:
    driver: bridge
